services:
  dashboard:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - 8080:8080
    environment:
      - DASH_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app/
    restart: unless-stopped
    # command: uv run python3 covid_dashboard_nl.py
