services:
  dashboard:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - 8080:8080
    environment:
      - DASH_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data:ro
      - ./assets:/app/assets:ro
    restart: unless-stopped
    # command: python3 covid_dashboard_nl.py